sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t mithunmohanraj/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mithunmohanraj/docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-601192085146"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


